# Generated by Django 2.2.6 on 2019-10-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipasaurus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='subject',
        ),
        migrations.AddField(
            model_name='deck',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
