# Generated by Django 2.2.6 on 2019-10-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipasaurus', '0002_auto_20191029_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
