# Generated by Django 2.2.6 on 2019-10-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipasaurus', '0004_auto_20191030_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
