# Generated by Django 2.2.6 on 2019-10-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipasaurus', '0005_auto_20191030_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', related_name='cards', to='flipasaurus.Deck'),
            preserve_default=False,
        ),
    ]
