# Generated by Django 2.2.6 on 2019-10-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipasaurus', '0004_auto_20191029_2202'),
        ('flipasaurus', '0006_auto_20191030_1816'),
    ]

    operations = [
    ]
