# Generated by Django 2.2.6 on 2019-11-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipasaurus', '0009_auto_20191101_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', related_name='cards', to='flipasaurus.Deck'),
        ),
    ]
